### ISSUE TITLE
Issue with wb_git_install applyCodebook

### ISSUE THREAD

**Issue by annnvv** [worldbank/stata#17]
Hello, 

I am trying to install applyCodebook and I get the following error :

. net install "https://raw.githubusercontent.com/worldbank/stata/master/wb_git_install/wb_git_install.pkg"
checking wb_git_install consistency and verifying not already installed...
installing into c:\ado\plus\...
installation complete.

. wb_git_install applyCodebook
unable to change to c:\ado\personal//a/
r(170);

I have STATA IC/15.1.

**Comment by bbdaniels** [comment]
Do the other programs install correctly if you try? It may be a Windows filepaths issue if they also fail and I can look into that.

**Comment by annnvv** [comment]
I tried importCodebook, but that did not work either for me.

**Comment by annnvv** [comment]
I discovered what my issue is. There are two ado folders on my C: drive. I put the .ado file into the ado folder that is in ProgramFiles/Stata 15/ado/personal instead of C://ado/personal. That made the difference.

**Comment by annak322** [comment]
In commit c81b73656f884ebfc084c2a8c4febcb4d1aed1ce, I resolved this issue by adding a line to create an "ado/personal" folder within the C:drive/ado folder @annnvv
