### ISSUE TITLE
long variable and value label names with applyCodebook.ado

### ISSUE THREAD

**Issue by miahpage** [worldbank/stata#18]
The program applyCodebook.ado breaks when the variable names or value label names are long due to limits on the length of local variables. 

I was able to do a quick work around by renaming long variables to a shorter name before running applyCodebook.ado and then renaming them back to the original variable name after running the program.

**Comment by bbdaniels** [comment]
What version of Stata are you running? I haven't restricted the version at all and Stata has been steadily increasing limit. Are you able to circumvent it by splitting the codebook into two files?

**Comment by miahpage** [comment]
I'm using Stata 15.1. I'm sorry for the confusion but this doesn't have to do with the size of the file but the length of the variable name.

If you use a variable name that is 32 characters then applyCodebook.ado breaks.

**Comment by bbdaniels** [comment]
For the variable limit this is a Stata limitation but I'll look more into the labeling one, thanks!

**Comment by miahpage** [comment]
Thank you for looking into this and I realize that I explained the issue poorly.

The issue with Stata limits occurs because the "length of a local macro name (characters)" is 31. On rows 21, 33, and 45 a local variable is created using the contents of the column varname from the input spreadsheet along with four additional characters (_lab, _ren, or _rec). If a Stata variable name in column varname is more than 28 characters, Stata's limit is 32 for variable names, then the code breaks because the local macro is too long.

**Comment by miahpage** [comment]
Instead of making the macro name "local `theVarname'_lab = varlab[`i']" could you use the `i' as the macro name? "local `i'_lab = varlab[`i']"

Then on row 22 you could create a macro with all of the variable names included in the macro and loop over this list later in the program when you need to use the variable names.

**Comment by bbdaniels** [comment]
A new version of this command, which we will release as part of a kit soon, should resolve this issue. Keep an eye out for `iefieldkit`! Closing this issue.
